### ISSUE TITLE
Double click on name with circumflex does not select entire word

### ISSUE THREAD

**Issue by Ben-Voris** [manoutoftime/vscode_tal#1]
Double-clicking on `a_b` selects the name but the same on `a^b` does not. As you know, TAL allows either an underscore or circumflex.

**Comment by manoutoftime** [comment]
First of all, I'm surprised that anybody out there actually uses this module. Considering how niche this is, I thought I was the only one. Hopefully, it mostly works for you.

Anyways... The selection on double click is something that VSCode controls itself. A simple language coloriser/tokenizer, such as this extension, does not alter that behaviour, or any behaviour for that matter.

What it does correctly is highlights a^b as a single variable in TAL. Where, on the other hand, in something like C a^b is considered variable a, operator ^ and variable b.

I will check VSCode documentation to see if that's something they introduced support for. But it's very unlikely.

**Comment by Ben-Voris** [comment]
Is this related? [Allow language extensions to override editor.wordSeparators](https://github.com/microsoft/vscode/issues/33701)

**Comment by manoutoftime** [comment]
Thank you for providing that info. I didn't know that was a thing. Unfortunately, that configuration is not available to extensions.

Someone opened an issue about this not to long ago: https://github.com/microsoft/vscode/issues/102942. I subscribed to the thread, so if they fix it, I'll add it.

There are two things I can do to make it a bit better:

**1**
There is a setting available to extensions that defines what a word is. But it does not affect editor actions. It should affect auto-completions and suggestions. So, a small improvement, hopefully.

https://code.visualstudio.com/api/language-extensions/language-configuration-guide#word-pattern

_wordPattern defines what's considered as a word in the programming language. Code suggestion features will use this setting to determine word boundaries if wordPattern is set. Note this setting won't affect word-related editor commands, which are controlled by the editor setting editor.wordSeparators._


Default wordPattern that includes ^ as a word separator.
![image](https://user-images.githubusercontent.com/447868/89594815-e0c85580-d820-11ea-9755-349a83d6f88b.png)

Overriding wordPattern to exclude ^ as a word separator makes editor highlight entire function name.
![image](https://user-images.githubusercontent.com/447868/89594905-2553f100-d821-11ea-9004-f9dba11a9771.png)

But it does seem to do more than that. Documentation says as much. It won't affect `editor.wordSeparators` editor commands.

**2**
I will update this extension description with instructions to add `editor.wordSeparator` settings to their user or workspace profile.

```
"[tal]": {
    "editor.wordSeparators": "`~!@#$%&*()-=+[{]}\\|;:'\",.<>/?"
}
```

**Comment by manoutoftime** [comment]
I found API settings for this.

https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults

```json
{
  "contributes": {
    "configurationDefaults": {
      "[markdown]": {
        "editor.wordWrap": "on",
        "editor.quickSuggestions": false
      }
    }
  }
}
```

This should do for TAL:

```json
{
    "configurationDefaults": {
        "[tal]": {
            "editor.wordSeparators": "`~!@#$%&*()-=+[{]}\\|;:'\",.<>/?"
        }
    }
}
```

**Comment by Ben-Voris** [comment]
The fix for this opens settings.json and adds a blank new line to the tal block each time the TAL language is selected. The files I'm editing have no extension, so I must use `Preferences` > `Configure Language Specific Settings`.

That is, if the settings.json contains:

```
"[tal]": {
      "editor.wordSeparators": "`~!@#%&*()-=+[{]}\\|;:'\",.<>/?"
  },
```

It will be updated to:

```
"[tal]": {
  
    "editor.wordSeparators": "`~!@#%&*()-=+[{]}\\|;:'\",.<>/?"
  },
````

The next time, another blank line is added.

**Comment by knovichikhin** [comment]
This does not happen to me. I opened a file without extension and assigned TAL language to this in various way. My `settings.json` did not change. I'm using VSCode 1.49.0
Also, I can assure you this extension does not try to open any files, least of all `settings.json`.

May I suggest a few things?
1. Try to install version prior to 0.1.1. You can right click on the extension and select "install another version".
2. Could it be some other extension doing this? You can try disabling other extension to see if it keeps happening.

General suggestions:
1. You don't have to have `"editor.wordSeparators"` configured for TAL in your `settings.json`. You can safely remove it because the extension itself sets it correctly.
2. You can have workplace settings set up for TAL files only and have TAL language assigned automatically to all files inside. Here is an example of what I use:

```json
{
    "folders": [
        {
            "path": "you_can_have_multiple_folders_in_a_workspace"
        },
        {
            "path": "another_folder"
        }
    ],
    "settings": {
        "files.associations": {
            "*.txt": "plaintext",
            "*.py": "python",
            "*": "tal"
        },
        "editor.rulers": [
            80
        ],
        "editor.autoIndent": "full",
        "editor.wordBasedSuggestions": false,
        "editor.detectIndentation": false
    }
}
```

https://stackoverflow.com/questions/29973619/how-to-make-vs-code-to-treat-other-file-extensions-as-certain-language

**Comment by Ben-Voris** [comment]
I am running Tandem TAL version 0.6.0.

I don't know how to install an older version of an extension, so I don't know how to revert to before 0.1.1.

VScode
```
Version: 1.49.2 (system setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

OS: Windows_NT x64 10.0.16299
```

The settings.json that is being changed is the per-user file, %APPDATA%\Code\User\settings.json, not the per-workspace file.

On your point about files without extensions, I use the SFTP plugin to get the files from /G. I have this in the `.vscode\settings.json` for the upload directory. As best I can tell, it has no effect which is why I change the language.

```
{
    "files.associations": {
	"memo": "plaintext",
	"softdoc": "plaintext",
	"*.*": "tal",
        "*": tal
    }
}
```

**Comment by knovichikhin** [comment]
To install another version, go to extensions tab, right-click on "Tandem TAL", "Install another version...". Let's try this first.

![image](https://user-images.githubusercontent.com/447868/94979646-f476fc00-04f1-11eb-94f1-ee4b99b3793b.png)

**Comment by Ben-Voris** [comment]
About handling Guardian files as TAL: the workspace  "files.associations" I showed above had two problems. And, because it was wrong, .vscode/settings.json was being treated as a TAL file, which meant that VScode didn't highlight the problem. Now that setting is:

```
{
    "files.associations": {
        "aareadme": "plaintext",
        "makefile": "Makefile",
        "readmemd": "Markdown",
        "softdoc": "plaintext",
        "*.json": "json", // Don't let the settings files use the default
        "*": "tal" // Anything not listed above will be treated as this language
    }
}
```

With this, the Guardian files I open are treated as TAL unless they match one of the previous patterns. And json files are opened as json files.
